name: gremlins

on:
  pull_request:

jobs:
  gremlins:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v6
        with:
          go-version: "stable"
          cache: true
      - uses: go-gremlins/gremlins-action@v1
        continue-on-error: true
        with:
          version: latest
          args: >-
            --threshold-efficacy=0
            --threshold-mcover=0
            handlers application infrastructure/searxng config
          workdir: .
